# Available levels: DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL
logging:
  level: "INFO"

mqtt:
  broker_host: "localhost"
  broker_port: 1883
  keepalive: 60
 
  publisher:
    client_id_prefix: "publish-"
    thing_id: "org.povo:phone"
    base_topic: "devices/in"
    publish_interval_seconds: 25
    num_messages: 5
    initial_translation: -30.0
    translation_increment: 10.0

  subscriber:
    client_id_prefix: "subscribe-"
    base_topic: "devices/out"

sionnart:
  script_name: "sionnart.py"