[project]
name = "ditto-sionnart-bridge"
version = "0.1.0"
description = "A bridge for real-time radio propagation analysis using Eclipse Ditto and SionnaRT."
readme = "README.md"
requires-python = ">=3.8, <3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
]
dependencies = [
    "sionna-rt==1.1.0",
    "tensorflow==2.19.0",
    "matplotlib==3.10.3",
    "paho-mqtt",
    "numpy",
    "loguru",
    "PyYAML"
]

[tool.uv]
dev-dependencies = []